### ISSUE TITLE
fix: 박스오피스 스케줄러

### ISSUE THREAD

**Issue by acs0209** [LG-URECA-FINAL-TEAM8/filmeet-backend#146]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## BUG 개요
DB로부터 제목으로 영화를 가져오는 부분에 문제가 발생해 캐시에 데이터가 담기지 않았습니다.
그래서 조회 쿼리를 수정하여 로컬 캐시에 박스오피스 순위 데이터가 담기지 않은 문제를 해결했습니다.

## TODO

- [ ] 이거 하려면 이런 걸 해야해
- [ ] 이것도 해야할 것 같아
